### ISSUE TITLE
scaling of the result

### ISSUE THREAD

**Issue by Zchappie** [kou1okada/libelas#3]
Hi, I tried this lib and it worked fine, but only one problem occurred.  
When I converted the output disparity map to depth value expressed in current camera frame, the depth seems relatively short. What I expected is something around 2 meters, but here I got  were around 0.3 meters.  
I also tested my rectification and converting disparity to depth with OpenCV, so I can say settings from disparity to depth is correct.  
My question is, does Libelas do some scaling on the output?

**Comment by kou1okada** [comment]
Please describe **specifically** how you converted depth from disparity.
I have no way to give you any helpful advice without it.

**Comment by Zchappie** [comment]
I found out my problem anyway. There is a scaling factor I used and I forgot to multiply it back. Sorry if the post has disturbed you.
