### ISSUE TITLE
Tips for resolving ERROR: Need at least 3 support points?

### ISSUE THREAD

**Issue by younesr1** [kou1okada/libelas#4]
Hello, I have two images that do not have a whole lot of features. When I try to generate the disparity map, I get an error saying "ERROR: Need at least 3 support points!". Do you have any tips on how to resolve this. Are there any internal parameters I could try to tweak?

I am very new to this so I apologise if there is an obvious answer to this

Thanks!

**Comment by younesr1** [comment]
![402_right (1)](https://user-images.githubusercontent.com/52610118/106496891-656ff580-648b-11eb-96b7-b264b39bbb9f.jpeg)
![402_left (1)](https://user-images.githubusercontent.com/52610118/106496920-6f91f400-648b-11eb-9dc1-ffd2d535bb4d.jpeg)

**Comment by kou1okada** [comment]
See issue #2.
You must adjust the epipolar constraint along the y-axis by using translation and rotation.

For example, adjusted right and left image as following:
![issue3-right](https://user-images.githubusercontent.com/1631846/106540118-a1b25d00-6542-11eb-862b-0eefc8e9fc34.jpeg)
![issue3-left](https://user-images.githubusercontent.com/1631846/106540122-a414b700-6542-11eb-953a-1d1c8f37e640.jpeg)
I adjusted them by the gimp.
And processing them:
```
$ ./elas issue3-left.pgm issue3-right.pgm
Processing: issue3-left.pgm, issue3-right.pgm
... done!
```
and results of right and left:
![issue3-right_disp](https://user-images.githubusercontent.com/1631846/106540172-c3abdf80-6542-11eb-8962-399c21d3bbb0.png)
![issue3-left_disp](https://user-images.githubusercontent.com/1631846/106540179-c73f6680-6542-11eb-8da9-36dea50e254e.png)

**Comment by younesr1** [comment]
Thank you for your response. Do you mind sharing the gimp cmds you used to rotate and translate the two images? Also, how did you arrive at the rotation and translation quantities needed for each picture? Lastly, am I correct in saying that the same rotation and translation would be needed for various images taken by the same stereo camera?

**Comment by younesr1** [comment]
Hello @kou1okada Unfortunately, I am still stuck on this. Does your code make the assumption that the pair of stereo images are rectified?
